# Generated by Django 3.1.7 on 2022-04-05 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todomodel',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='assigned_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
